### ISSUE TITLE
Consider including client's max validity period in CH DC extension

### ISSUE THREAD

**Issue by chris-wood** [tlswg/tls-subcerts#14]
If done, it seems the best path forward would be prohibiting servers from sending DCs with longer validity periods. This has a couple of benefits, and probably some downfalls:

1. Clients can "insist" on DC rotation with higher frequency than that which is ensured by servers.
2. It may simplify logic used to serve up DCs, especially if a server decides to offer "tiers" of DCs with different validity periods. 

Sending maliciously small validity periods seems to be no worse that the normal keyless design, wherein private key operations are shipped over the wire.

This might make clock synchronization worse, though. That is, if the client is unaware of its clock skew problem and offers a small validity period for DCs, then the likelihood of the connection failing should increase. (I don't have data to back this up. @siyengar might?)

**Comment by siyengar** [comment]
i looked up our data and the clock skew if the client's certificate validates correctly seems like it is within 1 day. While I think shorter validity is good, I don't think the client should dictate this. This is because the client might not have context about the server operators security model.

**Comment by grittygrease** [comment]
I think this adds complexity with minimal benefit. The client can’t dictate the max lifetime of certificates, for example.
