### ISSUE TITLE
Author affiliation

### ISSUE THREAD

**Issue by martinthomson** [tlswg/tls-subcerts#29]
Please double-check.  At least one of these appears to be wrong.

**Comment by siyengar** [comment]
were you looking at the editor copy perhaps, does the latest draft appear wrong as well? https://datatracker.ietf.org/doc/draft-ietf-tls-subcerts/

i think the editor copy went out of sync

**Comment by martinthomson** [comment]
Ahh. I was seeing Richard as being out of date.  I was also wondering if @ekr wanted to consider affiliation adjustment also.

**Comment by grittygrease** [comment]
@ekr Should we update your affiliation to Mozilla here?
