### ISSUE TITLE
Editor drafts are out-of-date

### ISSUE THREAD

**Issue by Lekensteyn** [tlswg/tls-subcerts#57]
The version posted at https://tlswg.org/tls-subcerts/draft-ietf-tls-subcerts.html is not up-to-date with git master. If this is being published from the gh-pages branch, note that that has not been updated since 2018-08-08.

Setting up a token per https://github.com/martinthomson/i-d-template/blob/master/doc/REPO.md#automatic-update-for-editors-copy should work.

Right [now](https://travis-ci.org/tlswg/tls-subcerts/builds/653119110) it pushes to a local folder which won't end up elsewhere:
```
git -C /tmp/ghpages4231 push origin gh-pages
Enumerating objects: 10, done.
Counting objects: 100% (10/10), done.
Delta compression using up to 2 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 23.60 KiB | 5.90 MiB/s, done.
Total 5 (delta 2), reused 0 (delta 0)
To /home/travis/build/tlswg/tls-subcerts/.
   fb76536..ac5c767  gh-pages -> gh-pages
```

**Comment by grittygrease** [comment]
I don't have the appropriate perms. @chris-wood mind adding the GH_TOKEN?

**Comment by chris-wood** [comment]
Should be fixed now!
