### ISSUE TITLE
Will the next version of draft define how to store delegated credential as file?

### ISSUE THREAD

**Issue by william-zk** [tlswg/tls-subcerts#62]
I found that there is no standard format for saving delegated credential in file, and I think it is necessary to define a standard format like pem or others.
Something like that:
------------Begin Delegated Credential-----------
....
------------End Delegated Credential-----------

**Comment by grittygrease** [comment]
This document describes the use of DCs in TLS, storage of DCs as files is out of scope and is up to the application, much like the DC distribution mechanism.
