### ISSUE TITLE
[WGLC] Clarify extension vs EKU usage

### ISSUE THREAD

**Issue by chris-wood** [tlswg/tls-subcerts#67]
From Russ:

I guess I ask the authors to add a paragraph to the rationale section that says something about why this extension was used instead of an extended key usage.

From Watson:

One of the hard requirements for our deployment was that the same
certificate be useable with DCs and without. A different EKU would be
more problematic then an extension for this purpose, and while it
might be more or less irritating for implementors depending on how
their stack works (sorry Rich -
https://boringssl-review.googlesource.com/c/boringssl/+/33666/1 might
serve as inspiration, but the client side got dropped for similar
issues). We know the extension doesn't bust things, I don't know an
EKU would, and the root program issues make me hesitate.

**Comment by grittygrease** [comment]
Addressed in #76
