### ISSUE TITLE
[WGLC] Address client clock skew

### ISSUE THREAD

**Issue by chris-wood** [tlswg/tls-subcerts#68]
From Martin:

I wonder how much more needs to be said about expiration dates and allowance for clock skew.  We haven't had any trouble with the mechanism proposed here (to my knowledge), but we've had plenty of trouble with ESNI deployment.  Maybe the design here is sufficiently superior that it is less susceptible to problems, but it's not clear that this is indeed the case.

Our implementation follows the spec when it comes to the validity period, but we can't really prevent skew from causing credentials to be rejected.  What this does is that it creates a fixed notBefore equivalent for the DC that is relative to the notAfter.  This effectively means that servers need to set valid_time values that aren't too far in the future based on their tolerance for client clock skew.  For a 7-day credential, you might get 5 good days of use.

A little bit of a nod in this direction might go a long way to avoiding deployment problems.

**Comment by grittygrease** [comment]
Fixed in #73
