### ISSUE TITLE
[WGLC] Note problems with DCs having lifetimes matching issuing certificates

### ISSUE THREAD

**Issue by chris-wood** [tlswg/tls-subcerts#69]
From Martin:

The security considerations don't cover the potential for misissuance creating a credential that is as long-lived as the certificate, but they probably should.

**Comment by grittygrease** [comment]
@martinthomson I'm not sure what you mean here. Are you talking about explicitly calling out the possibility that the credential may expire after the certificate and that this should be forbidden?

**Comment by martinthomson** [comment]
If you are able to access the signing key of the certificate, or are otherwise able to construct a DC, you can create multiple DCs that cover the time from now until the certificate expires.

It's not a big deal, but I thought it might be worth noting.

**Comment by grittygrease** [comment]
Gotcha. I'll note this.

**Comment by grittygrease** [comment]
Closed in #74
